name = "spoilershield-image-worker"
main = "src/index.ts"
compatibility_date = "2024-06-01"

[[r2_buckets]]
binding = "COMPETITION_LOGOS_BUCKET"
bucket_name = "competition-logos"
preview_bucket_name = "competition-logos"

[[r2_buckets]]
binding = "EVENT_LOGOS_BUCKET"
bucket_name = "event-logos"
preview_bucket_name = "event-logos"

[[r2_buckets]]
binding = "TEAM_LOGOS_BUCKET"
bucket_name = "team-logos"
preview_bucket_name = "team-logos" 